Repository IsyFact/isy-angular-widgets, pull requests merged in 2023-12, with the labels that each got.

#122 Isy 624 refactoring
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/app.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/app.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/chart/chart.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-informationsbereich/dashboard-informationsbereich.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-linksnavigation/dashboard-linksnavigation.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-widget/dashboard-widget.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/dashboard.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/services/date.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/menu-translation.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/menu-translation.service.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/validation/regex.ts
  projects/isy-angular-widgets-demo/src/test.ts
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
  projects/isy-angular-widgets/schematics/ng-add/package-config.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.spec.ts
  projects/isy-angular-widgets/src/lib/http/correlation-id-http-interceptor.spec.ts
  projects/isy-angular-widgets/src/lib/http/zipkin-open-tracing-http-interceptor.spec.ts
  projects/isy-angular-widgets/src/lib/i18n/widgets-config.service.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/data/regex.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.service.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.service.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-preview/input-char-preview.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.ts
  projects/isy-angular-widgets/src/lib/input-char/services/character.service.spec.ts
  projects/isy-angular-widgets/src/lib/security/security-guard.spec.ts
  projects/isy-angular-widgets/src/lib/security/security-service.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.ts
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.spec.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.spec.ts
  projects/isy-angular-widgets/src/test.ts
Labels: medium, ready for review

#123 Isy 631 mark wizard input fields as dirty
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/required-label/required-label.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/required-label/required-label.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/required-label/required-label.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/required-label/required-label.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.module.ts
  projects/isy-angular-widgets-demo/src/app/shared/validation/form-helper.ts
  projects/isy-angular-widgets-demo/src/app/shared/validation/form-helpers.spec.ts
Labels: fix, medium, ready for review

#117 Isy 574 invalid status in incomplete date fixed
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.scss
Labels: fix, medium, ready for review

#127 Isy 434 angular 17 migration
  angular.json
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/app-routing.module.ts
  projects/isy-angular-widgets/README.md
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css.map
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
Labels: medium, ready for review, dependencies

#128 Isy 633 fixed input group default width
  CHANGELOG.md
  projects/isy-angular-widgets/assets/theme/isyfact-theme.scss
Labels: fix, medium, ready for review

#131 Isy 684 disabled inputs better usability
  CHANGELOG.md
  projects/isy-angular-widgets/assets/theme/isyfact-theme.scss
Labels: fix, medium, ready for review

#124 Isy 576 moment deleted
  CHANGELOG.md
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
  projects/isy-angular-widgets/src/lib/validation/data/date-formats.ts
  projects/isy-angular-widgets/src/lib/validation/validation.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.ts
Labels: medium, ready for review

#134 fix: ISY-722 Fixed SonarQube errors
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/dashboard.component.ts
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
Labels: fix, medium, ready for review

#135 fix: ISY-722 Removed empty .scss files
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/chart/chart.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/chart/chart.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-informationsbereich/dashboard-informationsbereich.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-informationsbereich/dashboard-informationsbereich.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-linksnavigation/dashboard-linksnavigation.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-linksnavigation/dashboard-linksnavigation.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.ts
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.scss
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.ts
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.scss
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.scss
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.ts
Labels: fix, medium, ready for review

#136 Isy 722 code refactoring and sonar qube errors fix
  projects/isy-angular-widgets/src/lib/validation/data/date-formats.ts
Labels: fix, medium, ready for review

#137 ISY-614: CharPicker border radius fixed
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.html
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.spec.ts
Labels: medium, ready for review

#132 Isy 575 file upload
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.module.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/person-data.ts
  projects/isy-angular-widgets-demo/src/app/shared/model/person.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.ts
  projects/isy-angular-widgets-demo/src/assets/i18n/de.json
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
Labels: feat, medium, ready for review

#138 ISY-641: InputChar disabled and readonly fixed
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.ts
Labels: medium, ready for review

#140 feat: ISY-722 Updated outdated dependencies
  package-lock.json
  package.json
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
Labels: medium, ready for review, dependencies

#146 feat: ISY-722 Updated outdated dependencies
  package-lock.json
  package.json
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
Labels: medium, dependencies

#149 Isy 722 update outdated dependencies
  package-lock.json
  package.json
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
Labels: medium, ready for review, dependencies
