Repository IsyFact/isy-angular-widgets, pull requests merged in 2023-10, with the labels that each got.

#97 ci: ISY-450 add script to set version number from tag and validate first Changelog Entry
  .github/workflows/npm-publish.yml
  README.md
  package.json
  projects/isy-angular-widgets/package.json
Labels: ci, ready for review

#96 Feature/isy 468 refactoring
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/app.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/chart/chart.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-informationsbereich/dashboard-informationsbereich.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-linksnavigation/dashboard-linksnavigation.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-widget/dashboard-widget.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/dashboard.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/data/chart-init.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/country-data.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/person-data.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/services/date.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/menu-translation.service.spec.ts
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.html
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.spec.ts
  projects/isy-angular-widgets/src/lib/http/correlation-id-http-interceptor.spec.ts
  projects/isy-angular-widgets/src/lib/http/zipkin-open-tracing-http-interceptor.spec.ts
  projects/isy-angular-widgets/src/lib/i18n/widgets-config.service.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.service.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-preview/input-char-preview.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/services/character.service.spec.ts
  projects/isy-angular-widgets/src/lib/security/security-guard.spec.ts
  projects/isy-angular-widgets/src/lib/security/security-service.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.ts
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.spec.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.html
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.spec.ts
Labels: refactor, medium, ready for review

#98 fix: ISY-500 Liberation is now used as default fallback font
  CHANGELOG.md
  README.md
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css
Labels: fix, ready for review

#101 Isy 345 input autofill
  CHANGELOG.md
  package-lock.json
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.html
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.service.ts
Labels: ready for review

#108 Feature/isy 451 compodoc
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
  .gitignore
Labels: ready for review

#105 Feature/isy 360 add page not found route
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/routes.ts
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.html
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.scss
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/errors/page-not-found/page-not-found.component.ts
  projects/isy-angular-widgets-demo/src/app/shared/shared.module.ts
Labels: ready for review

#111 docs: ISY-468 Updated README
  README.md
Labels: ready for review
