Repository IsyFact/isy-angular-widgets, pull requests merged in 2023-11, with the labels that each got.

#112 docs: corrected some entries in CHANGELOG.md
  CHANGELOG.md
Labels: medium

#99 feat: ISY-144 Angular 16 Migration
  .eslintrc.js
  .prettierignore
  CHANGELOG.md
  README.md
  angular.json
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/app.component.ts
  projects/isy-angular-widgets-demo/src/app/app.permission.ts
  projects/isy-angular-widgets-demo/src/app/dropdown-permissions-data.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/data/chart-data.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/model/model.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.ts
  projects/isy-angular-widgets-demo/src/app/routes.ts
  projects/isy-angular-widgets-demo/src/app/shared/validation/validator.ts
  projects/isy-angular-widgets-demo/src/assets/permissions.json
  projects/isy-angular-widgets-demo/src/environments/environment.prod.ts
  projects/isy-angular-widgets-demo/src/environments/environment.ts
  projects/isy-angular-widgets-demo/src/main.ts
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
  projects/isy-angular-widgets/schematics/ng-add/package-config.ts
  projects/isy-angular-widgets/src/lib/i18n/widgets-config.service.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.html
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.service.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.spec.ts
  projects/isy-angular-widgets/src/lib/security/security-directive.ts
  projects/isy-angular-widgets/src/lib/validation/validation.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.ts
Labels: medium, ready for review

#120 feat: ISY-375 Mocked components
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.spec.ts
Labels: refactor, medium, ready for review, test
