Repository IsyFact/isy-angular-widgets, pull requests merged in 2024-03, with the labels that each got.

#181 fix: ISY-978 preventing linebreaks in table headers
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
Labels: fix, medium, ready for review

#183 Isy 978 fix prime ng tabe line break between icon and header
  CHANGELOG.md
Labels: docs, medium, ready for review

#182 Isy 907 add better contrast to hauptmenu
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.scss
Labels: feat, medium, ready for review

#170 ISY-538: Demo deployment with Github Pages
  .github/workflows/node.js.yml
  angular.json
  package.json
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/app.module.ts
  projects/isy-angular-widgets-demo/src/index.html
Labels: medium

#187 Isy 816 add filter sortierung to demo app
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.ts
  projects/isy-angular-widgets/src/lib/form-wrapper/public-api.ts
  projects/isy-angular-widgets/src/public-api.ts
Labels: ready for review

#188 Revert "feat: ISY-816 Added sorting and filters to demo application"
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.spec.ts
  projects/isy-angular-widgets-demo/src/app/shared/services/personen.service.ts
  projects/isy-angular-widgets/src/lib/form-wrapper/public-api.ts
  projects/isy-angular-widgets/src/public-api.ts
Labels: ready for review

#190 Isy 1014 fixed navbar overlapping
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.scss
Labels: fix, ready for review

#184 ISY-908: Update GitHub Actions
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
Labels: medium

#169 Isy 919 input char refactoring
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
  projects/isy-angular-widgets-demo/src/assets/i18n/de.json
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
  projects/isy-angular-widgets/assets/i18n/de.json
  projects/isy-angular-widgets/assets/i18n/en.json
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.html
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.html
  projects/isy-angular-widgets/src/lib/input-char/components/input-char/input-char.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/multi-select-button/multi-select-button.component.html
  projects/isy-angular-widgets/src/lib/input-char/components/multi-select-button/multi-select-button.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/multi-select-button/multi-select-button.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/multi-select-button/multi-select-button.component.ts
  projects/isy-angular-widgets/src/lib/input-char/directives/input-char.directive.ts
  projects/isy-angular-widgets/src/lib/input-char/input-char.module.ts
  projects/isy-angular-widgets/src/lib/input-char/model/model.ts
  projects/isy-angular-widgets/src/lib/input-char/services/character.service.ts
Labels: refactor, medium, ready for review

#191 Isy 1044 capture multiple output values
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/data.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.module.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.html
  projects/isy-angular-widgets-demo/src/app/shared/model/person.ts
  projects/isy-angular-widgets-demo/src/assets/i18n/de.json
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
Labels: feat, medium, ready for review
