Repository IsyFact/isy-angular-widgets, pull requests merged in 2024-02, with the labels that each got.

#165 ISY-389: Imports to demo app via library name added
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/app.component.ts
  projects/isy-angular-widgets-demo/src/app/app.module.ts
  projects/isy-angular-widgets-demo/src/app/app.permission.ts
  projects/isy-angular-widgets-demo/src/app/core/user/userInfoPublicService.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.module.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.module.ts
  projects/isy-angular-widgets-demo/src/app/routes.ts
  tsconfig.json
Labels: ready for review, low

#164 Isy 634 demo app responsive overhaul
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/assets/i18n/de.json
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
Labels: medium, ready for review

#166 ISY-775: Updated readme files for standalone projects
  CHANGELOG.md
  README.md
  package.json
  projects/isy-angular-widgets/README.md
Labels: medium, ready for review

#168 Isy 647 floating labels
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.scss
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/persoenliche-informationen/persoenliche-informationen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/required-label/required-label.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css
  projects/isy-angular-widgets/assets/theme/isyfact-primeng-bootstrap-light.css.map
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.html
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
Labels: medium, ready for review

#172 Isy 876 bottom-right toast-notifications
  CHANGELOG.md
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.module.ts
Labels: feat, medium, ready for review

#173 Isy 919 code refactoring
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/app.component.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/dashboard.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/components/dialog-sachverhalte-bearbeiten/dialog-sachverhalte-bearbeiten.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/components/result-list/result-list.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.html
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.html
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.spec.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.html
  projects/isy-angular-widgets/src/lib/security/security-directive.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.html
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.spec.ts
Labels: refactor, medium, ready for review

#177 feat: ISY-906 Added HTML landmarks
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/assets/i18n/de.json
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
  projects/isy-angular-widgets/assets/i18n/de.json
  projects/isy-angular-widgets/assets/i18n/en.json
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.html
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.spec.ts
Labels: feat, medium, ready for review

#175 Isy 877 add field to form wrapper
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/form-wrapper/form-wrapper.component.html
  projects/isy-angular-widgets/src/lib/form-wrapper/form-wrapper.component.spec.ts
  projects/isy-angular-widgets/src/lib/form-wrapper/form-wrapper.component.ts
Labels: feat, medium, ready for review

#176 ISY-874: Sticky side toolbar added to hauptfenster
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/app.component.html
  projects/isy-angular-widgets-demo/src/app/app.module.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/components/seitentoolbar/seitentoolbar.component.html
  projects/isy-angular-widgets/src/lib/hauptfenster/components/seitentoolbar/seitentoolbar.component.scss
  projects/isy-angular-widgets/src/lib/hauptfenster/components/seitentoolbar/seitentoolbar.component.spec.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/components/seitentoolbar/seitentoolbar.component.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.html
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.spec.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.ts
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.module.ts
Labels: medium, ready for review

#178 feat: ISY-919 Updated outdated dependencies
  package-lock.json
Labels: feat, medium, ready for review

#179 Isy 919 improve test coverage
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/objekt-suchen.component.spec.ts
  projects/isy-angular-widgets-demo/src/assets/i18n/en.json
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
Labels: medium, ready for review, test
