Repository IsyFact/isy-angular-widgets, pull requests merged in 2024-01, with the labels that each got.

#150 Isy 722 dashboard test runtime error fix
  package-lock.json
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-widget/dashboard-widget.component.html
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-widget/dashboard-widget.component.spec.ts
  projects/isy-angular-widgets-demo/src/app/feature/dashboard/components/dashboard-widget/dashboard-widget.component.ts
  projects/isy-angular-widgets/package-lock.json
Labels: medium, ready for review, test

#152 feat: ISY-722 Updated outdated dependencies
  package-lock.json
  package.json
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
Labels: medium, ready for review, dependencies

#145 Isy 722 refactoring wizard
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.html
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.spec.ts
  projects/isy-angular-widgets/src/lib/wizard/components/stepper/stepper.component.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.html
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.spec.ts
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.ts
  projects/isy-angular-widgets/src/lib/wizard/wizard.module.ts
Labels: refactor, medium, ready for review

#157 Isy 722 sonarcloud fixes
  package-lock.json
  package.json
  projects/isy-angular-widgets-demo/src/app/feature/objekt-suchen/person-data.spec.ts
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
Labels: fix, medium, ready for review

#144 Revert/isy 576
  CHANGELOG.md
  package-lock.json
  package.json
  projects/isy-angular-widgets/package-lock.json
  projects/isy-angular-widgets/package.json
  projects/isy-angular-widgets/schematics/ng-add/index.ts
  projects/isy-angular-widgets/src/lib/validation/data/date-formats.ts
  projects/isy-angular-widgets/src/lib/validation/validation.spec.ts
  projects/isy-angular-widgets/src/lib/validation/validation.ts
Labels: medium

#143 ISY-618: Incomplete date widget also accepts normal date entry with dot
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.spec.ts
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
Labels: medium, ready for review

#163 Isy 682 incomplete date pipe
  CHANGELOG.md
  projects/isy-angular-widgets/src/lib/pipes/data/errors.ts
  projects/isy-angular-widgets/src/lib/pipes/data/regex.ts
  projects/isy-angular-widgets/src/lib/pipes/incomplete-date.pipe.spec.ts
  projects/isy-angular-widgets/src/lib/pipes/incomplete-date.pipe.ts
Labels: medium, ready for review

#162 Isy 630 accessibility lang tag
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/app.component.ts
Labels: medium, ready for review

#159 Isy 756 theme revised splitted
  CHANGELOG.md
  projects/isy-angular-widgets-demo/src/app/feature/objekt-anzeigen/objekt-anzeigen.component.ts
  projects/isy-angular-widgets/assets/theme/isyfact-theme.scss
  projects/isy-angular-widgets/src/lib/hauptfenster/hauptfenster.component.scss
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.html
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.scss
  projects/isy-angular-widgets/src/lib/incomplete-date/incomplete-date.component.ts
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-dialog/input-char-dialog.component.scss
  projects/isy-angular-widgets/src/lib/input-char/components/input-char-preview/input-char-preview.component.scss
  projects/isy-angular-widgets/src/lib/wizard/components/wizard/wizard.component.spec.ts
Labels: high, ready for review
